name: flight_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.0+1
  injectable: ^2.5.1
  get_it: ^8.3.0
  equatable: ^2.0.7
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0
  flutter_localization: ^0.3.3
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.0
  intl: ^0.19.0
  flutter_form_builder: ^9.7.0
  custom_sliding_segmented_control: ^1.8.5
  calendar_date_picker2: ^2.0.1
  icons_plus: ^5.0.0
  form_builder_validators: ^11.1.2
  flutter_libphonenumber: ^2.5.1
  scrollable_positioned_list: ^0.3.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  skeletonizer: ^1.4.3
  dotted_border: ^2.1.0
  flutter_svg: ^2.2.0
  upgrader: ^12.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  lints: ^5.1.1
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
