name: flight_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.0+1
  injectable: ^2.5.1
  get_it: ^8.3.0
  equatable: ^2.0.7
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0
  flutter_localization: ^0.3.3
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  lints: ^5.1.1

flutter:
  uses-material-design: true
  generate: true
